### ISSUE TITLE
Feature: User can sort and view more pages in the leaderboard

### ISSUE THREAD

**Issue by rohan-fowlerharper** [mako-hammerhead-2022/pets-n-pats#7]
## User Story

As a user, I'd like to be able to explore ALL the pets that the site has to offer. On the leaderboards page, I'd like to be able to sort the pets by 'most points' or 'least points' so that I can show love for pets that haven't been discovered yet.

## Your job

- Investigate [react-table](https://react-table-v7.tanstack.com/) v7 (v8 documentation isn't quite complete) and discuss here whether it is a good fit for this task
- Tasks specific to this ticket will be added below as comments as they are discussed.

**Comment by rupert-denton** [comment]
Having reviewed React Table we think it would be an appropriate resource for this feature - especially because it has  pagination hook (usePaginate)
